---
- name: Show in-memory inventory with add_host
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  - name: Get server info
    os_server_info:
      cloud: openstack
    register: r_os_server_info

