---
- name: Show in-memory inventory with add_host
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  - name: Get server info
    os_server_facts:
      cloud: openstack
    register: r_os_server_info
    
  - debug: var=r_os_server_info

  - name: Add hosts
    add_host:
      name: "{{ item.name }}"
      ansible_host: "{{ item.public_v4 }}"
      ansible_user: cloud-user
      ansible_ssh_private_key_file: ~/.ssh/test_id_rsa
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
      groups:
      - "{{ item.metadata.group }}"
    loop: "{{ r_os_server_info.ansible_facts.openstack_servers }}"
    loop_control:
      label: "{{ item.name }}"
    
- name: Configure servers
  hosts: testservers
  gather_facts: false
  tasks:
  - ping: {}
