---
- name:                 Configuration of repositories
  hosts:                all
  gather_facts:         false 
  roles:
    - enable_repo

- name:                 Deploy haproxy
  hosts:                apps, frontends
  gather_facts:         true
  become:               true
  tasks:
  - name:               Run deploy_haproxy role
    include_role:
      name:             deploy_haproxy
    when: >-
      'frontends' in group_names

- name:                 Deploy tomcat
  hosts:                apps
  gather_facts:         false
  become:               true
  roles:
    - install_tomcat

- name:                 Deploy postgres
  gather_facts:         false
  become:               true
  hosts:                appdbs
  roles:
    - install_postgres


- name:                 Deploy apache
  hosts:                apps
  gather_facts:         false
  become:               true
  roles:
    - install_apache
